### ISSUE TITLE
Check handle

### ISSUE THREAD

**Issue by FXTi** [FXTi/iocp-wrapper#17]
appear in wepoll when get a handle from tree struct.

But it's meaningful to check in some case, it requires split some critical functions.

Refs: wepoll.c: 724L-725L

**Comment by piscisaureus** [comment]
In wepoll, `err_check_handle()` is used only when an error happened.
See https://github.com/piscisaureus/wepoll/blob/e9bf27c395f97d81fd216eb26434d9dcdebcb013/wepoll.c#L722-L725

The purpose of wepoll is to match linux' `epoll_ctl()` behavior as close as possible. 
On linux, if you call `epoll_ctl()` with an invalid file descriptor *and* an invalid `op`, it'll return -1 and set `errno` to `EBADF` and not `EINVAL`.
The only purpose of `err_check_handle()` is to make sure that `errno` is always set to `EBADF` if either the epoll handle or the socket was invalid.

I don't think it is necessary to port this feature, since your goal is not to emulate epoll().

**Comment by FXTi** [comment]
I agree, the file descriptor provided will not be invalid, since it's all internal implementation.

`Selector::check_iocp_port()` is removed
